# Generated by Django 3.1.1 on 2021-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_pwd', models.CharField(max_length=20)),
                ('stu_email', models.CharField(max_length=50)),
                ('stu_course', models.CharField(max_length=100)),
                ('stu_role', models.CharField(max_length=1)),
            ],
        ),
    ]
